import type { Metadata } from "next";
import { Frank_Ruhl_Libre } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import InfoBar from "./components/InfoBar";

const frl = Frank_Ruhl_Libre({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${frl.className} flex min-h-screen flex-col overflow-x-hidden`}
      >
        <InfoBar />
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
